"""
Policy and eligibility rules for insurance recommendations.

This module implements a simple rules engine to ensure that
recommendations generated by the ML model respect regulatory and
business constraints.  At the moment rules are configured via YAML
files in the ``data/product_knowledge`` directory.  Each product can
specify minimum/maximum ages, required signals, or any other flags
deemed necessary by the business.  A separate exclusions file
specifies global rules such as "never recommend already owned
products".
"""

from __future__ import annotations

from typing import Dict, List, Optional
import yaml
import os
from pathlib import Path
from datetime import datetime

from .schemas import ClientProfile, RecommendationResult, PolicyDecision


DEFAULT_RULES_PATH = Path("data/product_knowledge/product_rules.yaml")
DEFAULT_EXCLUSIONS_PATH = Path("data/product_knowledge/product_exclusions.yaml")


def load_product_rules(rules_path: Path = DEFAULT_RULES_PATH) -> Dict[str, Dict[str, any]]:
    """Load the per‑product eligibility rules from a YAML file.

    Each top‑level key in the YAML corresponds to a product code.  The
    values are dictionaries with rule parameters (e.g. ``min_age``,
    ``max_age``, ``requires_income_signal``).

    Returns an empty dict if the file does not exist or cannot be
    parsed.
    """
    if not rules_path.exists():
        return {}
    try:
        with open(rules_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
            return data
    except Exception:
        return {}


def load_exclusions(exclusions_path: Path = DEFAULT_EXCLUSIONS_PATH) -> Dict[str, List[Dict[str, any]]]:
    """Load global exclusion rules from a YAML file.

    The file should define a ``global`` section with a list of
    dictionaries containing ``rule`` and optional ``severity`` keys.
    For now this function simply returns the dictionary as loaded
    without enforcing any semantics on the severity.
    """
    if not exclusions_path.exists():
        return {}
    try:
        with open(exclusions_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
            return data
    except Exception:
        return {}


def _get_age(profile: ClientProfile) -> Optional[int]:
    """Best effort retrieval of the client's age from the profile.

    Looks for ``age`` in ``extra_info`` or attempts to compute it from
    ``birth_year``.  Returns ``None`` if both are missing.
    """
    if profile.extra_info is None:
        return None
    if "age" in profile.extra_info and profile.extra_info["age"]:
        try:
            return int(profile.extra_info["age"])
        except Exception:
            pass
    if "birth_year" in profile.extra_info and profile.extra_info["birth_year"]:
        try:
            birth_year = int(profile.extra_info["birth_year"])
            return datetime.now().year - birth_year
        except Exception:
            pass
    return None


def apply_policy_rules(
    profile: ClientProfile,
    rec: RecommendationResult,
    product_rules: Optional[Dict[str, Dict[str, any]]] = None,
    exclusions: Optional[Dict[str, List[Dict[str, any]]]] = None,
) -> PolicyDecision:
    """Apply business and eligibility rules to the recommendation list.

    This function enforces the following policies:

    * Products already owned by the client are always blocked.
    * Minimum and maximum ages per product (if defined) are checked.
    * Placeholder for additional rules such as required signals or
      business constraints.

    Parameters
    ----------
    profile: ClientProfile
        The client's profile.
    rec: RecommendationResult
        The raw recommendation output from the ML engine.
    product_rules: Optional[Dict[str, Dict[str, any]]]
        The ruleset loaded from YAML.  If ``None`` the default path
        will be used.
    exclusions: Optional[Dict[str, List[Dict[str, any]]]]
        Global exclusions loaded from YAML.  Currently only the
        ``global`` section is read.  If ``None`` the default file is
        used.

    Returns
    -------
    PolicyDecision
        Object summarising allowed and blocked products with reasons.
    """
    # Load rules/exclusions if not provided
    if product_rules is None:
        product_rules = load_product_rules()
    if exclusions is None:
        exclusions = load_exclusions()
    global_rules = exclusions.get("global", []) if exclusions else []

    allowed: List[str] = []
    blocked: List[str] = []
    reasons: Dict[str, str] = {}

    # Compute client age once
    age = _get_age(profile)

    # Process each recommended product
    for product_code, score in rec.filtered_scores.items():
        # Always skip products with -inf score or missing
        if score == float("-inf"):
            continue
        # Rule 1: already owned products must not be recommended
        if product_code in profile.current_products:
            blocked.append(product_code)
            reasons[product_code] = "already owned"
            continue
        # Rule 2: product specific age constraints
        pr_rules = product_rules.get(product_code, {})
        if age is not None:
            min_age = pr_rules.get("min_age")
            max_age = pr_rules.get("max_age")
            if min_age is not None and age < min_age:
                blocked.append(product_code)
                reasons[product_code] = f"age {age} < min_age {min_age}"
                continue
            if max_age is not None and age > max_age:
                blocked.append(product_code)
                reasons[product_code] = f"age {age} > max_age {max_age}"
                continue
        # Additional product rules could be enforced here
        # Placeholder: requires_income_signal
        if pr_rules.get("requires_income_signal"):
            # Without an implementation of income signal detection we
            # conservatively block the product
            blocked.append(product_code)
            reasons[product_code] = "income signal required"
            continue
        # Global exclusions (e.g. never recommend a forbidden product)
        forbidden = False
        for rule in global_rules:
            if rule.get("rule") == "do_not_recommend_already_owned_product":
                # Already handled above
                continue
            # Unknown global rules are ignored
        if forbidden:
            blocked.append(product_code)
            reasons[product_code] = "globally excluded"
            continue
        # If we reach here the product is allowed
        allowed.append(product_code)
    return PolicyDecision(allowed=allowed, blocked=blocked, reasons=reasons)
